actions:
  eslint:
    description: eslint
    run: yarn eslint {files}
    fix: yarn eslint --fix {files}
    include:
      - "*.js"
    exclude:
      - ".eslintrc.js"
      - ".prettierrc.js"
  typescript:
    description: Typescript type checking
    run: yarn tsc --noEmit --project tsconfig.json
    include:
      - "extension/content/*.js"
      - "extension/content/*.ts"
      - "extension/content/*.tsx"
  stylelint:
    run: yarn stylelint {files}
    include:
      - "*.css"
      - "*.less"

shortcuts:
  lint:
    flags:
      - include-unstaged
      - include-untracked
  "lint:all":
    extends: lint
    flags: use-tracked-files
  fix:
    extends: lint
    flags: fix
  "fix:all":
    extends: fix
    flags: use-tracked-files
